services:
  app:
    build:
      context: .
    ports:
      - "3400:3400"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    tty: true
    environment:
      - ENV=local
    command: sh -c "go mod tidy && go run cmd/masmaint-cg/main.go"