services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    tty: true
    environment:
      ENV: local
    command: sh -c "go mod tidy && go run cmd/masmaint/main.go"

  db:
    image: mysql:8.0.34
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: masmaint
      TZ: Asia/Tokyo
    volumes:
      - ./my.ini:/etc/mysql/conf.d/my.cnf
      - ./scripts:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql